### ISSUE TITLE
What database used when training smoking-faces model

### ISSUE THREAD

**Issue by vimers** [chok68/smoking-faces#1]

**Comment by chok68** [comment]
Unfortunately I could not find datasets with people smoking so I used images from the sample video (labeled around 30%)

**Comment by vimers** [comment]
there are some videos labed with smoking in HMDB database.but the resolution is too small

**Comment by xinliu111** [comment]
Hi, i am looking for smoking videos, would you like to share the dataset  you found with me?  my email:  Awaylest@163.com  thank you very much.

**Comment by chok68** [comment]
@xinliu111 Refer to https://github.com/chok68/smoking-faces/issues/1#issuecomment-472318730
