### ISSUE TITLE
training code

### ISSUE THREAD

**Issue by xinliu111** [chok68/smoking-faces#3]
Thanks for your sharing! could you please provide training code to me? I hope I can get your help, thank you very much.

**Comment by chok68** [comment]
You're welcome.

The original tutorial I first followed is this: https://medium.freecodecamp.org/tracking-the-millenium-falcon-with-tensorflow-c8c86419225e

Similar approach here (haven't tested it) https://androidkt.com/train-object-detection/

Hope this helps!

**Comment by xinliu111** [comment]
The two links you sent cannot be opened. Could you provide another link or send a source code to my email Awaylest@163.com? Thank you very much

**Comment by chok68** [comment]
Those are tutorials for the tensorflow object detection. You can also try this: this: https://github.com/tensorflow/models/tree/master/research/object_detection 

Sorry but I cannot send such codes directly to you.
