### ISSUE TITLE
module 'pylab' has no attribute 'frange'

### ISSUE THREAD

**Issue by lankunyao** [chok68/smoking-faces#5]
When I try to run the code, I find that it has a attributeerror which says module 'pylab' has no attribute 'frange'. Does anyone know how to solve this problem?

**Comment by chok68** [comment]
Maybe this is causing the issue?

mlab.frange (use numpy.arange instead)

Please see: https://matplotlib.org/3.1.0/api/api_changes.html

**Comment by lankunyao** [comment]
> Maybe this is causing the issue?
> 
> mlab.frange (use numpy.arange instead)
> 
> Please see: https://matplotlib.org/3.1.0/api/api_changes.html

Yeah, that's the solution, I've solved it, thx!
